name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: sudo apt-get install libhiredis1.1.0 libhiredis-dev

    - name: Build
      run: make

    - name: On release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: telly
