name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: sudo apt-get install libhiredis1.1.0 libhiredis-dev gperf libjemalloc2 libjemalloc-dev

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build -- -j$(nproc)

    - name: On release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/telly
